# Generated by Django 3.2 on 2023-03-21 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldetail',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
